networks:
  inception:            # The name of the network
    name: inception     # Explicitly sets the network name
    driver: bridge      # Uses the bridge network driver (default Docker network type)

secrets:
  secret_enc:                     # The name of the first secret
    file: ~/secrets/secrets.enc   # Path to the encrypted secrets file on your host
  secret_key:                                # The name of the second secret
    file: ~/secrets/vault/decryptionKey.txt  # Path to the decryption key file

volumes:
  db_data:                  # The name of the volume
    name: db_data           # Explicitly sets the volume name
    driver: local           # Uses the local volume driver
    driver_opts:            # Options for the driver
      type: none            # Specifies a bind mount (not a volume with a filesystem)
      device: ~/data/db     # The host path to mount (in your home directory)
      o: bind               # Mount option specifying this is a bind mount

services:
  mariadb:                     # The service name
    build: ./requirements/mariadb  # Path to the Dockerfile for building this service
    container_name: mariadb    # Explicitly names the container (otherwise would be auto-generated)
    image: mariadb:42          # The image name:tag to use (or create when building)
    
    volumes:                   # Mounts storage to the container
      - db_data:/var/lib/mysql  # Uses the named volume "db_data" for database storage
      - ~/secrets/secrets.enc:/run/secrets/secrets.enc:ro  # Mounts host file as read-only
    
    secrets:                   # Docker secrets to inject into the container
      - secret_key             # Makes the "secret_key" available inside the container
    
    env_file:                  # Environment variables file
      - ~/secrets/.env         # Loads environment variables from this file
    
    restart:                   # Container restart policy
      on-failure:7             # Restart up to 5 times if container exits with non-zero code
    
    expose:                    # Ports exposed only to other containers (not to host)
      - "3306"                 # Standard MariaDB/MySQL port
    
    networks:                  # Networks this container connects to
      - inception              # Connects to the "inception" network defined elsewhere
    
    healthcheck:               # Container health monitoring configuration
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]  # Command to check if DB is healthy
      interval: 11s            # Run the check every 11 seconds
      timeout: 7s              # Health check times out after 7 seconds
      retries: 7               # Number of consecutive failures before marking unhealthy
    
    logging:                   # Log handling configuration
      driver: "json-file"      # Use JSON file format for logs
      options:
        max-file: "7"          # Keep up to 7 log files
        max-size: "7m"        # Each log file can be up to 7 megabytes
